# Generated by Django 4.1.1 on 2022-10-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ('id',), 'verbose_name': 'Cart Product', 'verbose_name_plural': 'Cart Products'},
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_products', to='cart.cart'),
        ),
    ]
