# Generated by Django 4.1.1 on 2022-09-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_vote_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='points',
        ),
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.CharField(blank=True, choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=15, null=True),
        ),
    ]
