# Generated by Django 4.1.1 on 2022-09-30 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_remove_vote_points_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestion',
            name='dislikes',
            field=models.ManyToManyField(related_name='question_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='likes',
            field=models.ManyToManyField(related_name='question_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
