# Generated by Django 4.1.1 on 2022-09-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productquestion_dislikes_productquestion_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
