# Generated by Django 4.1.1 on 2022-10-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='wished_products',
        ),
    ]
