# Generated by Django 4.1.1 on 2022-10-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_coupon_options_alter_coupon_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
